import type { Question } from './types';

export const QUESTIONS: Question[] = [
  {
    id: 'nombre-empresa',
    type: 'text',
    question: '¿Cuál es el nombre de su empresa?',
    description: 'Información básica',
    placeholder: 'Escriba aquí el nombre...',
    required: true,
  },
  {
    id: 'dedica-empresa',
    type: 'text',
    question: '¿A qué se dedica su empresa?',
    description: 'Actividad de la empresa',
    placeholder: 'Describa su actividad...',
    required: true,
  },
  {
    id: 'control-negocio',
    type: 'choice',
    question: '¿Tiene claridad diaria sobre cuánto vende y gana su empresa?',
    description: 'Control del negocio',
    options: ['Sí', 'No'],
    required: true,
  },
  {
    id: 'gestion-informacion',
    type: 'choice',
    question: '¿Cómo gestiona actualmente la información de su negocio?',
    description: 'Gestion informacion',
    options: [
      'A. Sistema automatizado',
      'B. Herramientas digitales (Excel, apps)',
      'C. Manual',
      'D. No hay control claro'
    ],
    required: true,
  },
  {
    id: 'procesos-internos',
    type: 'choice',
    question: '¿Existen tareas repetitivas que su equipo hace manualmente todos los días?',
    description: 'Procesos internos',
    options: ['Sí', 'No'],
    required: true,
  },
  {
    id: 'errores-procesos',
    type: 'choice',
    question: '¿Ha tenido errores o pérdidas por procesos manuales o desorganización?',
    description: 'Errores procesos',
    options: ['Sí', 'No'],
    required: true,
  },
  {
    id: 'ventas',
    type: 'choice',
    question: '¿Tiene un proceso de ventas definido y medido?',
    description: 'Ventas',
    options: ['Sí', 'No'],
    required: true,
  },
  {
    id: 'seguimiento-clientes',
    type: 'choice',
    question: '¿Hace seguimiento a clientes que no compran en el primer contacto?',
    description: 'Seguimiento clientes',
    options: ['Sí', 'No'],
    required: true,
  },
  {
    id: 'clientes-datos',
    type: 'choice',
    question: '¿Cuenta con una base de datos organizada de sus clientes?',
    description: 'Clientes y datos',
    options: ['Sí', 'No'],
    required: true,
  },
  {
    id: 'tecnologia-oportunidades',
    type: 'choice',
    question: '¿Sus herramientas actuales están conectadas entre sí (ej: ventas, clientes, operaciones)?',
    description: 'Tecnología y oportunidades',
    options: ['Sí', 'No'],
    required: true,
  },
  {
    id: 'interes-automatizacion',
    type: 'choice',
    question: '¿Le gustaría automatizar procesos para ahorrar tiempo y vender más?',
    description: 'Interes automatizacion',
    options: ['Sí', 'No'],
    required: true,
  },
  {
    id: 'whatsapp',
    type: 'text',
    question: 'Déjanos tu número de WhatsApp para comunicarnos contigo y agendar una cita',
    description: 'Contacto',
    placeholder: 'Ej: +57 300 000 0000',
    required: true,
  },
];

